# Conclusion {-}

The goal of this thesis was to compare the homotypic vacuole fusion processes of _S. cerevisiae_ and _A. thaliana_. I was originally drawn to this project while researching guard cell vacuole fusion in _A. thaliana_. During that process, I saw many papers eluding to the conserved nature of homotypic vacuole fusion. Furthermore, many papers investigating guard cell vacuole fusion used _S. cerevisiae_ homotypic vacuole fusion as a model to contextualize the process of _A. thaliana_ vacuole fusion. Therefore, I decided to investigate the similarities and differences between the PPIs in each process. Using the K-hop algorithm I constructed layered graph representations of the PPIs in both _A. thaliana_ guard cell vacuole fusion and _S. cerevisiae_ homotypic vacuole fusion. Analysis of each layer indicated that, while there were a number of conserved PPIs, the two processes had many inconsistencies. The largest diffence between the two vacuole fusion processes lies in the synthesis, modification, and function of phosphoinositides. In comparison to _S. cerevisiae_, _A. thaliana_ guard cell vacuole fusion utilizes phosphoniositide singaling to a far greater extent. While PPI graphs are useful for generalized visualizations and analysis, they fail to capture more complex aspects of signaling pathways. Therefore, given that phosphoinositide singaling seems to play a large role in guard cell vacuole fusion, including phosphorylation events, lipid interactions, and other singaling pathway components may allow for a deeper analysis of the role that phosphoinositides play in guard cell vacuole fusion.

